### ISSUE TITLE
Q formation looked at instead of Modron formation.

### ISSUE THREAD

**Issue by Emmotes** [imp444/IC_Addons#1]
Heya

Thought it might be an idea in the `DoPartySetupMin` and `DoPartySetupMax` to use the Modron formation instead of the Q formation.

By swapping:
`formationFavorite1 := g_SF.Memory.GetFormationByFavorite( 1 )`
to
`formationModron := g_SF.Memory.GetActiveModronFormation()`
and correcting any `formationFavorite1` references.

This way it can cope with people using extra champions in W that aren't in Q by using a separate Modron formation with more champions.

**Comment by imp444** [comment]
Hi, 

Using Modron formation instead of Q requires to have the champions on the bench already swapped in so they can be leveled up using F keys.
This doesn't work with Tatyana as she shares the same slot as Hew Maan.

**Comment by imp444** [comment]
Hi,

Using Modron formation instead of Q requires to have the champions on the bench already swapped in so they can be leveled up using F keys.
This doesn't work with Tatyana as she shares the same slot as Hew Maan.

**Comment by imp444** [comment]
I could a

**Comment by Emmotes** [comment]
Yeah that did cross my mind as a potential problem. They'd have to be on the bench - and levelling only Q at least forces that to be the case. Hmm.

No matter then. Was just an idle thought that came up when I was planning an 11j route. Was considering adding Egbert to E so that in cases where if it lands on a boss (particularly the clown) - the group can kill it without Briv.

**Comment by imp444** [comment]
I see, you're talking about the case where you fail to swap back to Q or have a failed conversion and are forced to walk to the stacking zone. This works for 11J as you don't have to cancel Briv's animation anymore so extra E champs don't matter.
I guess special event triggers could be added for that, so champions seats that are not used in E could be leveled up until maxLevel for such cases.
