### ISSUE TITLE
IC_RNGWaitingRoom_Extra : If DM+Familiars is used to refresh the ult cooldown, the script doesn't realise you've ulted

### ISSUE THREAD

**Issue by CodeKalias** [imp444/IC_Addons#4]
https://github.com/imp444/IC_Addons/blob/8fa844c2ca7c750b850bb3f61372e66d0623e392/IC_RNGWaitingRoom_Extra/IC_RNGWaitingRoom_Functions.ahk#L220

Since the ult gets refreshed immediately by familiars the script doesn't realise the ult has been used
Symptoms of this are additional redraws being done and incorrect stats being recorded
- A 2/1/On setup will try to try to draw 3 hands of cards instead of 2 and will record redraw stats incorrectly
- A 2/2/On setup will try to try to draw 4 hands of cards instead of 3 and will record redraw stats incorrectly
- A 2/999/On setup will functionally work fine, but still record incorrect redraw stats

Probably only an issue while there's no built in DM functionality

**Comment by imp444** [comment]
This is fixed in v0.2.2.
