### ISSUE TITLE
Tatyana active on offline stack (Hybrid Turbo)

### ISSUE THREAD

**Issue by Extraversi0n** [imp444/IC_Addons#7]
Hello,
the option _If Melf's effect is not active: Stack online with Tayana_ also makes her offline stack on a zone where melfs effect is not active, which is likely to occur, the less favor you have and slightly increases stacks due to healthshare being enabled.
![image](https://github.com/user-attachments/assets/e7528859-ea3f-4318-b326-1d3695f4d6e0)

Best regards,
Extraversi0n

**Comment by imp444** [comment]
I guess you want to always offline stack (either triggered when ForeceOfflineRun threshold has been reached or the option to offline when Melf is not active) without Tatyana and Warden?

**Comment by Extraversi0n** [comment]
I mean, do I need them when I offline stack? It explicitly says that it will use tatyana instead of melf for online stacking. Hence my confusion when it also happens on the offline stack. Not sure if that was the intent or not. Seemed weird to me

**Comment by imp444** [comment]
Scripthub always want to you to have the exact same formation on the field as the one saved in the second slot (W).
Otherwise it will get stuck trying switch back after stacking.
Currently, the addon handles this during the online part of stacking ,but not while offline stacking, so it would need another exception for that case.

**Comment by Extraversi0n** [comment]
But if my fixed offline stack zone in the run I go offline is not on a melf
speed zone melf is supressed to be fielded and only tatyana is present, so
the exception is already working. It is just also working when it
shouldn't? Or maybe I misunderstood what it was supposed to be doing

imp444 ***@***.***> schrieb am Di., 26. Nov. 2024, 23:45:

**Comment by imp444** [comment]
Right now, the addon will only modify the stack formation when online stacking.
If you are able to stack offline with Tatyana but not Melf while having both saved in W, then this is not normal behavior.

**Comment by Extraversi0n** [comment]
yeah, that is what is happening. (only when the melf speed effect is not active in the stacking zone though)

**Comment by Extraversi0n** [comment]
> Right now, the addon will only modify the stack formation when online stacking. If you are able to stack offline with Tatyana AND without Melf while having both saved in W, then this is not normal behavior.

I made another recording. but you are right. it does field melf AND Tatyana.  melf is **NOT** excluded from the formation. not sure what I was seeing.

**Comment by imp444** [comment]
Melf, Tatyana and Warden are removed from the offline stack formation in [v1.1.2](https://github.com/imp444/IC_Addons/commit/5dfd66c3b3d2bf66f36bde1b1e8704c7db0fa931)
